version: '3.8'

services:
  # MongoDB Exporter for Prometheus
  mongo-exporter:
    image: percona/mongodb_exporter:0.40
    container_name: iam-mongo-exporter
    restart: unless-stopped
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: mongodb://iam_admin:IamAdmin123@mongo:27017/admin?authSource=admin
    depends_on:
      - mongo
    networks:
      - iam-network

  # Prometheus (optional - for metrics collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: iam-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - iam-network

  # Grafana (optional - for visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: iam-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana-datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - iam-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  iam-network:
    external: true
